### ISSUE TITLE
Increase size of pool to create cards from

### ISSUE THREAD

**Issue by glacay30** [devbrock/rocketleague-bingo#1]
The current implementation has a fixed number of available items to choose from (24 total), and applies a shuffle to the `tasks` object to obtain a randomized card.

However, to increase the number of total items, the object would need to be filled with 24 items rather than already having all those items already. This can be done by storing the items in a separate object where the `create()` method would then fill the `tasks` object with 24 randomly selected items from the separate object and then return `tasks`.

To start, here are all the items from [Rizzo's bingo video](https://youtu.be/i_Ul_K_68Qs?t=154):
* juicy fake
* missing an open net
* toxic chat
* flip reset
* passing play
* forfeit before 2:30
* DEMO RAMPAGE
* laggy server
* 0 second goal
* we steal each other's boost
* juicy own goal
* risky backpass
* musty flick
* score off a demo
* fat whiff
* throw a game in the final minute
* idiot stops playing instead of forfeiting
* ball hovers over goalline
* prejump goal
* insane pinch
* ceiling shot
* ask Rizzo for a sign
* 3 goals (hat trick)
* get into rule #1

**Comment by jettucker** [comment]
Seems it's already written to randomly pull 24 items from the list. Really nothing needs to be done but add more items to that list. You made it sound way more complicated than it was.

**Comment by devbrock** [comment]
Another system will take the place of the local list of challenges that are stored in the tasks object. This is only a temporary solution to get the project off the ground.
